# Generated by Django 5.2.6 on 2025-09-24 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_badge_description_reward_link_alter_badge_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointreason',
            name='default_coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointreason',
            name='default_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ActivityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('points', models.PositiveIntegerField(default=0)),
                ('coins_change', models.IntegerField(default=0, help_text='Coins earned (positive) or spent (negative)')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='main.enrollment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
