# Generated by Django 5.2.6 on 2025-09-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pointreason_default_coins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgecriteria',
            name='badge',
        ),
        migrations.DeleteModel(
            name='AwardedBadge',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='BadgeCriteria',
        ),
    ]
