# Generated by Django 5.2.6 on 2025-10-13 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_group_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityentry',
            name='linked_point_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pointentry'),
        ),
    ]
