# Generated by Django 5.2.6 on 2025-10-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_activityentry_linked_point_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityentry',
            name='for_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointentry',
            name='for_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
