# Generated by Django 5.2.6 on 2025-10-15 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_activityentry_for_date_pointentry_for_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YTInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('admin', models.OneToOneField(limit_choices_to={'is_stafff': True, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='yt_admin_instance', to=settings.AUTH_USER_MODEL)),
                ('coordinators', models.ManyToManyField(limit_choices_to={'is_stafff': True, 'is_superuser': False}, related_name='yt_coordinators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'YouTrack Instance',
            },
        ),
    ]
