# Generated by Django 5.2.6 on 2025-10-15 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_ytinstance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytinstance',
            name='admin',
            field=models.OneToOneField(limit_choices_to={'is_staff': True, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='yt_admin_instance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ytinstance',
            name='coordinators',
            field=models.ManyToManyField(limit_choices_to={'is_staff': True, 'is_superuser': False}, related_name='yt_coordinators', to=settings.AUTH_USER_MODEL),
        ),
    ]
