# Generated by Django 5.2.6 on 2025-10-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_ytinstance_admin_alter_ytinstance_coordinators'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytinstance',
            name='point_reasons',
            field=models.ManyToManyField(blank=True, related_name='yt_point_reasons', to='main.pointreason'),
        ),
    ]
